server {
  listen 80;
  server_name _;

  # arquivos estão sob /usr/share/nginx/html/catalogo-virtual
  location /catalogo-virtual/ {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /catalogo-virtual/index.html;
  }

  location ~* ^/catalogo-virtual/.*\.(css|js|mjs|png|jpe?g|gif|svg|ico|webp|woff2?)$ {
    root /usr/share/nginx/html;
    expires 7d;
    add_header Cache-Control "public, max-age=604800, immutable";
    try_files $uri =404;
  }

  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options SAMEORIGIN;
  add_header X-XSS-Protection "1; mode=block";
}
