server {
  listen 80;
  server_name _;

  # (opcional) bloqueia raiz
  location = / { return 404; }

  # Serve seu app em /catalogo-virtual/
  location /catalogo-virtual/ {
    # raiz dos arquivos estáticos
    root /usr/share/nginx/html;

    # SPA fallback (Vite/React)
    try_files $uri $uri/ /catalogo-virtual/index.html;
  }
}
